export interface KorgStyle {
  name: string;
}

export interface KorgBank {
  id: string;
  label: string;
  color: 'green' | 'red';
  styles: KorgStyle[];
}

export interface KorgPerformanceBank {
  bankName: string;
  items: KorgStyle[];
}

export interface KorgPadBank {
  bankName: string;
  items: KorgStyle[];
}

export interface KorgSoundBank {
  bankName: string;
  items: (KorgStyle | null)[];
}

const SOUND_PAGES_PER_BANK = 16;
const SOUND_SLOTS_PER_PAGE = 8;
const SOUND_SLOTS_PER_BANK = SOUND_PAGES_PER_BANK * SOUND_SLOTS_PER_PAGE;

export const KORG_SET_DATA: Record<string, KorgBank> = {
  FAVORITE01: {
    id: 'FAVORITE01',
    label: 'Popular',
    color: 'green',
    styles: [
      { name: 'Mars-mVi' },
      { name: 'Geampara-mVi' },
      { name: 'Gagauzia-mVi' },
      { name: 'Doina-mVi' },
      { name: 'MultiAni-mVi' },
      { name: 'HoraMasa-mVi' },
      { name: 'HoraRara-mVi' },
      { name: 'Hora-mVi' },
      { name: 'Batuta-mVi' },
      { name: 'Sirba-mVi' },
      { name: 'SirbaToba-mVi' },
      { name: 'SirbaRara-mVi' },
      { name: 'SirbHincesti-mVi' },
      { name: 'BatHancesti-mVi' },
      { name: 'Hora_Ialoveni-Vi' },
      { name: 'Brau 6,7,8-mVi' },
      { name: 'Ardeal-mVi' },
      { name: 'Ascultare-mVi' },
      { name: 'Rustem&Breaz-mVi' },
      { name: 'Bucovina-mVi' },
      { name: 'Maramures-mVi' },
      { name: 'Balcanica-mVi' },
      { name: 'Hora Nuca-GKY' },
      { name: 'Ruseasca-GKY' },
      { name: 'Banat de joc' },
    ],
  },
  FAVORITE02: {
    id: 'FAVORITE02',
    label: 'Etno',
    color: 'green',
    styles: [
      { name: 'HoraEtno-mVi' },
      { name: 'SarbaEtno-mVi' },
      { name: 'HoraEtno2-mVi' },
      { name: 'SirbaEtno2-mVi' },
      { name: 'Raiburg-mVi' },
      { name: 'Tortul' },
      { name: 'Etno Vechi - mVi' },
    ],
  },
  FAVORITE03: {
    id: 'FAVORITE03',
    label: 'Usoara',
    color: 'green',
    styles: [
      { name: 'Sora si frat-mVi' },
      { name: 'Sarut femeie-mVi' },
      { name: 'Seara minuna-mVi' },
      { name: 'Ce nas ce nasa' },
      { name: 'Laskovii Mai-mVi' },
      { name: 'Shanson-mVi' },
      { name: 'Darite jensh-mVi' },
      { name: 'DiscoMD-mVi' },
      { name: 'Taburcean-mVi' },
      { name: 'Colind-mVi' },
      { name: 'Vals-mVi' },
      { name: 'Lozanciuc-mVi' },
      { name: 'AleargaCaii-mVi' },
      { name: 'LacrimaAmara-mVi' },
      { name: 'RussianStyle-mVi' },
      { name: 'RussianBlues-mVi' },
      { name: 'EstrMD - mVi' },
      { name: 'Lady-mVi' },
      { name: 'Form.Prut - mVi' },
      { name: 'Dumitras - mVi' },
      { name: 'Butyrka - mVi' },
      { name: 'Dolina-mVi' },
      { name: 'Pinguinul-mVi' },
      { name: 'Django' },
      { name: '7/40' },
      { name: 'MT-Brother Louie' },
      { name: 'Lambada' },
      { name: 'Despacito' },
      { name: 'Bossa-Lite' },
      { name: 'Melancolie' },
      { name: 'Jingle Bells' },
      { name: 'Evr-Portnoi' },
    ],
  },
  FAVORITE04: {
    id: 'FAVORITE04',
    label: 'Manele ',
    color: 'green',
    styles: [
      { name: 'Manea-mVi' },
      { name: 'Manea2-mVi' },
      { name: 'Mahalarai-mVi' },
      { name: 'Basgali-mVi' },
      { name: 'Saint Tropez' },
      { name: 'Suna Fata-mVi' },
      { name: 'Made in RO-mVi' },
      { name: 'ManeaMahala-mVi' },
      { name: 'NoapteRece - mVi' },
      { name: 'Azur - mVi' },
    ],
  },
  FAVORITE05: {
    id: 'FAVORITE05',
    label: 'Obicei',
    color: 'green',
    styles: [
      { name: 'Ascultare-mVi' },
      { name: 'Hora-mVi' },
      { name: 'Ciocirlia - mVi' },
      { name: 'Doina-mVi' },
    ],
  },
  FAVORITE06: {
    id: 'FAVORITE06',
    label: 'nHore',
    color: 'green',
    styles: [
      { name: 'PorniLaJoc-am155' },
      { name: 'PoruncitB-Eb140' },
      { name: 'Nashule-cm165' },
      { name: 'AstasLume-cm152' },
      { name: '5Chiperi-gm160' },
      { name: 'JoacaSocri-dm142' },
    ],
  },
  FAVORITE07: {
    id: 'FAVORITE07',
    label: 'nSarbe',
    color: 'green',
    styles: [
      { name: 'LaZileMari-cm' },
      { name: 'CeFrumViata-G' },
      { name: 'PrinStraini-fm' },
    ],
  },
  FAVORITE08: {
    id: 'FAVORITE08',
    label: 'nUsoara',
    color: 'green',
    styles: [{ name: 'Balerina-A - mVi' }, { name: 'JumatateTu-Dm' }],
  },
  FAVORITE09: {
    id: 'FAVORITE09',
    label: 'iHore',
    color: 'green',
    styles: [
      { name: 'Hora-E142-mVi' },
      { name: 'Breaza-gm165-mVi' },
      { name: 'iHora-C155' },
      { name: 'iTigan-C140' },
      { name: 'BatTromp-C140' },
    ],
  },
  FAVORITE10: {
    id: 'FAVORITE10',
    label: 'iSarbe',
    color: 'green',
    styles: [{ name: 'Sarb_Ion-A217-mVi' }, { name: 'iSarba-D180' }],
  },
  USER01: {
    id: 'USER01',
    label: 'User 1',
    color: 'red',
    styles: [],
  },
  USER02: {
    id: 'USER02',
    label: 'User 2',
    color: 'red',
    styles: [],
  },
  USER03: {
    id: 'USER03',
    label: 'User 3',
    color: 'red',
    styles: [
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
    ],
  },
};

export const KORG_PERFORMANCE_DATA: Record<string, KorgPerformanceBank> = {
  FAVORITE01: {
    bankName: 'Piano',
    items: [{ name: 'Piano' }],
  },
  FAVORITE02: {
    bankName: 'E. Piano',
    items: [
      { name: 'MANUAL' },
      { name: 'MUTED' },
      { name: 'Orchest. viori 1' },
      { name: 'Acc Burduf' },
    ],
  },
  FAVORITE03: {
    bankName: 'Mallet & Bell',
    items: [
      { name: 'Vibraphone' },
      { name: 'Vibes&Oct.Piano' },
      { name: 'Vibes & Jazz Gtr' },
      { name: 'Vibes & Steel Dr' },
      { name: 'Bell & Whistle' },
      { name: 'Bell & Flute' },
      { name: 'Bell & Accordion' },
      { name: 'Marimba Trill' },
      { name: 'Bell Pad Voice' },
      { name: 'Tropical' },
      { name: 'Music Box' },
    ],
  },
  FAVORITE04: {
    bankName: 'Accordion',
    items: [
      { name: 'Supita' },
      { name: 'Acord. Juzi 1' },
      { name: 'Mussete fr8' },
      { name: 'Noapte rece si p' },
      { name: 'Cantora Live' },
      { name: 'Acordeon Sup Cla' },
    ],
  },
  FAVORITE05: {
    bankName: 'Organ',
    items: [{ name: 'Junosti-mVi' }],
  },
  FAVORITE06: {
    bankName: 'Guitar',
    items: [
      { name: 'Chitara Turnenii' },
      { name: 'Distortion Gtr' },
      { name: 'Nylon Guitar' },
      { name: 'Electric Guitar' },
      { name: 'Carlos Guitar' },
    ],
  },
  FAVORITE07: {
    bankName: 'Strings & Vocal',
    items: [
      { name: 'ORCH PA1 BUN' },
      { name: 'Orchestra buna' },
      { name: 'Orchestra2' },
      { name: 'Orchestra%' },
      { name: 'Acord+Orch' },
      { name: 'Acord+Orch2' },
      { name: 'Vioara maramures' },
      { name: 'Zeta Real' },
      { name: 'Genos' },
      { name: 'Viori normale' },
      { name: 'Smooth Orchestra' },
      { name: 'Strings & Bell' },
      { name: 'Violin' },
      { name: 'Tuti' },
    ],
  },
  FAVORITE08: {
    bankName: 'Trumpet & Trbn.',
    items: [{ name: 'Trompeta Solo 2' }, { name: 'Trompta+Clarinet' }],
  },
  FAVORITE09: {
    bankName: 'Brass',
    items: [
      { name: 'Bras 510' },
      { name: 'Sforzato Brass' },
      { name: 'La nunta asta' },
      { name: 'Mars' },
      { name: 'Brass ciocoi' },
      { name: 'Lacramioara' },
    ],
  },
  FAVORITE10: {
    bankName: 'Sax',
    items: [
      { name: 'Taragot' },
      { name: 'Sax Tarata' },
      { name: '---' },
      { name: 'Taragoata' },
      { name: 'Taragot-Orch' },
    ],
  },
  FAVORITE11: {
    bankName: 'Woodwind',
    items: [
      { name: 'Ocarina' },
      { name: 'Toarna-n pahare' },
      { name: 'Nai + Clarinet' },
      { name: 'Azur-Iubita' },
      { name: 'Clarinet evr' },
      { name: 'Flute Frulatto' },
      { name: 'Bottle Flute-mVi' },
      { name: 'Panflute & Synth' },
      { name: 'Clarinet' },
      { name: 'Fleita Juzisound' },
      { name: 'Fluier Kronos' },
      { name: 'NaiReal + Clar' },
      { name: 'Nai Real' },
      { name: '---' },
      { name: 'caliope-nai' },
      { name: 'Fluieras folclor' },
      { name: 'Caval AD' },
    ],
  },
  FAVORITE12: {
    bankName: 'Synth Pad',
    items: [
      { name: 'Sarut femeie min' },
      { name: 'Darite jenshinam' },
      { name: 'Seara minunata' },
      { name: 'Lacrima Amara' },
      { name: 'Intinde o mina' },
      { name: 'Inima nu ma lasa' },
      { name: 'Pa2X Pad' },
      { name: 'Bell Disco' },
      { name: 'Gliding Pad' },
      { name: 'Fresh Bell Pad' },
      { name: 'Fresh Bell Pad 2' },
      { name: 'Fresh Bell Pad 3' },
      { name: 'Synth Pad' },
      { name: 'Sora si frate' },
      { name: 'Big One 2' },
      { name: 'Fresh Bell Pad' },
      { name: 'Noisy Stabb' },
      { name: 'Bad Pad' },
    ],
  },
  FAVORITE13: {
    bankName: 'Synth Lead',
    items: [
      { name: 'Lady' },
      { name: 'Insor in mai' },
      { name: 'Big Lead Sine' },
      { name: 'Saw Lead' },
      { name: 'Big Lead Sine 2' },
      { name: 'Dalina' },
    ],
  },

  FAVORITE14: {
    bankName: 'Ethnic',
    items: [
      { name: 'Cortan' },
      { name: 'Klarnet Oct.' },
      { name: 'Kanun & Klarnet' },
      { name: 'Yayli Grup' },
      { name: 'Ret. Ciocoi' },
      { name: 'Zurna Turcia' },
      { name: 'Cumbus M3' },
      { name: 'Synth Lead' },
    ],
  },
  FAVORITE15: {
    bankName: 'Bass',
    items: [
      { name: 'Finger Bass' },
      { name: 'Jazz Ac. Bass' },
      { name: 'Funk Slap Bass' },
      { name: 'Bass & Ride Cym' },
      { name: 'Piano Trio' },
      { name: 'Entert.Organ1' },
      { name: 'Entert.Organ2 V.' },
      { name: 'Entert.Organ3 Y+' },
      { name: 'Entert.Organ4 V.' },
      { name: 'Entert.Organ5' },
      { name: 'Entert.Organ6 V.' },
      { name: 'Real Theatre Org' },
      { name: 'Th. Organ Voice' },
    ],
  },
  FAVORITE16: {
    bankName: 'Drum & SFX',
    items: [
      { name: 'Standard Kit Amb' },
      { name: 'Vintage Kit Amb' },
      { name: 'Gate Kit Amb' },
      { name: 'Standard Kit RX2' },
      { name: 'Standard Kit RX3' },
      { name: 'Pop Standard Kit' },
      { name: 'Standard PercKit' },
      { name: 'Special FX Kit' },
    ],
  },
};

export const KORG_PAD_DATA: Record<string, KorgPadBank> = {
  USER01: {
    bankName: 'User 1',
    items: [
      { name: 'Mars-dm142' },
      { name: 'Mars-gm140' },
      { name: 'Balcanica-hm170' },
      { name: '---' },
      { name: 'Geampara-A125' },
      { name: 'Geamp-f#-128' },
      { name: 'Ghiughiuliu-dm' },
      { name: 'Lilita Ioana-A' },
      { name: 'Babadag-E130' },
      { name: 'Kadinca-cm115' },
    ],
  },
  USER02: {
    bankName: 'User 2',
    items: [
      { name: 'SirbRar-dm160' },
      { name: 'Sirb nord-cm190' },
      { name: 'SirbaNord2 c-190' },
      { name: 'Vaiuku-dm210' },
      { name: 'Costiuleni1-bm' },
      { name: 'Costiuleni2 - Bb' },
      { name: 'Zirnesti-cm205' },
      { name: 'SrSava-am195' },
      { name: 'In caruta - C215' },
      { name: 'Sirba-Bb195' },
      { name: 'Basmaluta-F-NL' },
      { name: 'Tofan-Sirba-D180' },
      { name: 'SarbIon-A-217' },
    ],
  },
  USER03: {
    bankName: 'User 3',
    items: [],
  },
  USER04: {
    bankName: 'User 4',
    items: [],
  },
  USER05: {
    bankName: 'User 5',
    items: [],
  },
  USER06: {
    bankName: 'User 6',
    items: [
      { name: 'Sanie zurg-em135' },
      { name: 'Pandelescu-em135' },
      { name: 'O Mie-E120' },
      { name: 'Hora C-125 ' },
      { name: 'Onoriu-Hor E-121' },
      { name: 'Hora fm130' },
      { name: 'Hora Bb128' },
      { name: 'Hora-fm140' },
      { name: 'Batuta D-168' },
      { name: 'Hor-Srbeas_A_155' },
      { name: 'Hangul-am136' },
      { name: 'Hora A-131' },
      { name: 'Hora A 150' },
      { name: 'Hora-C 160' },
      { name: 'Hora-C170' },
      { name: 'Batuta-Bb-190' },
      { name: 'Hora-Bb-165' },
      { name: 'Hora Iugosl-C150' },
      { name: 'Hora Sud-Bb-175' },
      { name: 'Batuta Bb-175' },
      { name: 'Batuta-G 155-190' },
      { name: 'Batut-Bb 150-175' },
      { name: 'Lordeni hm-156' },
      { name: 'PoartaNunul-130F' },
      { name: 'Hora-D125' },
      { name: 'Laut-Nord-fm130' },
      { name: 'HoraNord2-F-135' },
      { name: 'Hr-Margin-140_hm' },
      { name: 'Hora cm-130' },
      { name: 'Hanganu-dm136' },
      { name: 'Hora-dm-138' },
      { name: 'HoraVesel1-dm134' },
    ],
  },
  USER07: {
    bankName: 'User 7',
    items: [
      { name: 'HoraVesel2-E138' },
      { name: 'Hai Catrina-D115' },
      { name: 'Mai Cobzare-D120' },
      { name: 'Hora Balti -A125' },
      { name: 'Btuta-A160' },
      { name: 'Hora am128' },
      { name: 'Hora-am143' },
      { name: 'Hora C-135' },
      { name: 'Chitrilor-gm130' },
      { name: 'Hora-cm135' },
      { name: 'Batuta B-178' },
      { name: 'Saltareata-am132' },
      { name: 'Strengarit-dm132' },
      { name: 'MdrLaHora-135 dm' },
      { name: 'HorPrimire-136fm' },
      { name: 'Hora-hm128' },
      { name: 'Bucuresti-Bb110' },
      { name: 'HrDeMana-C130' },
      { name: 'Gasitoi-dm138NL' },
      { name: 'Hora D138' },
      { name: 'Batuta H155' },
      { name: 'Sup de mic f#89' },
      { name: 'HrBorog-C135NL' },
      { name: 'Olareasca-A130' },
    ],
  },
  USER08: {
    bankName: 'User 8',
    items: [],
  },
  USER09: {
    bankName: 'User 9',
    items: [],
  },
  USER10: {
    bankName: 'User 10',
    items: [
      { name: 'Tha-Thaaaa' },
      { name: 'Rain Stick' },
      { name: 'CHIUITI BA' },
    ],
  },
};

export const KORG_SOUND_DATA: Record<string, KorgSoundBank> = {
  USER01: {
    bankName: 'User 1',
    items: [
      { name: 'Acordeon Juzi' },
      { name: 'Ac. 2017Florin F' },
      { name: 'Acordeon Supita' },
      { name: 'Cantora S' },
      { name: 'Supita S5 KLA' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: 'ORCH.7-CTL' },
      { name: 'Vioara maramures' },
      { name: 'ORCH-ALEX' },
      { name: 'Taraf viori 1' },
      { name: 'Zeta Real2' },
      { name: 'Orchestra fanfar' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: 'Trompeta' },
      { name: 'TROMP-CLARN' },
      { name: 'Trombon Moldova*' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Sax Alto 1' },
      { name: 'Taragot' },
      { name: 'Taragoata' },
      { name: 'SaxFluier Cioco2' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Fluieras Kronos' },
      { name: 'Caval' },
      { name: 'Fluieras folclor' },
      { name: 'Fleita Juzisound' },
      { name: 'Nai Real' },
      { name: 'Clarinet' },
      { name: 'CALIOPE D50' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: 'Nexus Studio' },
      { name: 'Junosti-mVi' },
      { name: 'Pluck Synth CP' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: 'Cortan' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },

      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
    ],
  },
  USER02: {
    bankName: 'User 2',
    items: [
      { name: 'Bass Touch Gaby' },
      { name: 'Bs tras scurt' },
      { name: 'Bass Etno' },
      { name: 'Koky Studio' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Clean RX' },
      { name: 'Nylon+braci Gab2' },
      { name: 'DX Pratnja' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Braci ff nou*' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Tambal Doina' },
      { name: 'Tambal Stereo 2' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: 'Etno Drums' },
      { name: 'Etno fill 1' },
      { name: 'manea 4' },
      { name: '---' },
      { name: 'CHIUIT FAIN' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
    ],
  },
  USER03: {
    bankName: 'User 3',
    items: Array(128).fill(null),
  },

  USER04: {
    bankName: 'User 4',
    items: Array(128).fill(null),
  },
  USER05: {
    bankName: 'User 5',
    items: Array(128).fill(null),
  },
  USER06: {
    bankName: 'User DK',
    items: [
      { name: 'Toba FolclDorin' },
      { name: 'Set-Nunta 2' },
      { name: 'Shanson' },
      { name: 'EtnoMD' },
      { name: 'Raiburg-mVi' },
      { name: '---' },
      { name: '---' },
      { name: 'Laskovii Mai 2' },
      { name: 'Manea Modern' },
      { name: 'SONOR LIVE 1 MAR' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
      { name: '---' },
    ],
  },
};
